databases:
  - name: postgres
    ipAllowList: []
    databaseName: transact_api
    user: transact_api

services:
  - type: web
    name: transact_api
    env: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false